import { madokaGet, madokaPost, madokaPut } from "@/utils/request.ts"

// LR_小さな狐の妖精: true 使用模拟数据，false 使用真实API
const USE_MOCK_DATA = false

// LR_小さな狐の妖精: 留言板模拟数据，因为该死的跨域请求
const mockMessageData = {
  "list": [
    {
      "id": 47097,
      "pid": 0,
      "userId": 12,
      "externalId": 7,
      "externalUserId": null,
      "externalUsername": null,
      "likes": 1,
      "image": null,
      "avatar": null,
      "content": "圆神午安，刚刚睡醒） 睡了个大懒觉呢，超爱这种一觉自然醒的感觉hhh",
      "origin": "madokami",
      "deleted": 0,
      "createTime": 1771558355002,
      "username": "霜冻",
      "userUpdateTime": 1771520136,
      "liked": 0,
      "replies": [
        {
          "id": 47098,
          "pid": 47097,
          "userId": 1,
          "externalId": 0,
          "externalUserId": null,
          "externalUsername": null,
          "likes": 0,
          "image": null,
          "avatar": null,
          "content": "( • ⩊ • )",
          "origin": "madokami",
          "deleted": 0,
          "createTime": 1771565042144,
          "username": "鹿目圆",
          "userUpdateTime": 1769172312,
          "liked": 0,
          "replies": []
        }
      ]
    },
    {
      "id": 47096,
      "pid": 0,
      "userId": 13,
      "externalId": 6,
      "externalUserId": null,
      "externalUsername": null,
      "likes": 0,
      "image": null,
      "avatar": null,
      "content": "(•́⌄•́๑)૭✧",
      "origin": "madokami",
      "deleted": 0,
      "createTime": 1771519817513,
      "username": "InQbit",
      "userUpdateTime": 1771520106,
      "liked": 0,
      "replies": []
    },
    {
      "id": 47095,
      "pid": 0,
      "userId": 12,
      "externalId": 5,
      "externalUserId": null,
      "externalUsername": null,
      "likes": 0,
      "image": null,
      "avatar": null,
      "content": "阿圆超棒WWWWWW ",
      "origin": "madokami",
      "deleted": 0,
      "createTime": 1771519642623,
      "username": "霜冻",
      "userUpdateTime": 1771520136,
      "liked": 0,
      "replies": []
    },
    {
      "id": 47037,
      "pid": 0,
      "userId": null,
      "externalId": 43233,
      "externalUserId": 6291,
      "externalUsername": "JupiterEur",
      "likes": 1,
      "image": "",
      "avatar": null,
      "content": "圆神晚安~",
      "origin": "kami.im",
      "deleted": 0,
      "createTime": 1770301920000,
      "username": null,
      "userUpdateTime": null,
      "liked": 0,
      "replies": []
    },
    {
      "id": 47094,
      "pid": 0,
      "userId": null,
      "externalId": 6658,
      "externalUserId": 1505,
      "externalUsername": "李",
      "likes": 0,
      "image": "639058959607594289,639058959607623780",
      "avatar": null,
      "content": "圆焰晚上好，今天也是特别开心跟好朋友去玩了剧本杀，玩的情感本哭的稀里哗啦的，还有幸去了趟朋友家看看，她带着我介绍了附近，从中午玩到九点多才打车回家，大家人都特别好，真的很开心 ˃ ꇴ ˂\n希望以后也能生活也能每天开开心心，幸福每一天呢ദ്ദി˶•̀֊•́)✧\n\n给你们看看我之前抽的圆神和焰酱，也是在努力攒抽抽焰魔，凑个对\n\n\n",
      "origin": "madohomu.love",
      "deleted": 0,
      "createTime": 1770299160000,
      "username": null,
      "userUpdateTime": null,
      "liked": 0,
      "replies": []
    },
    {
      "id": 47093,
      "pid": 0,
      "userId": null,
      "externalId": 6657,
      "externalUserId": 1557,
      "externalUsername": "魔法",
      "likes": 0,
      "image": "639058796645642924",
      "avatar": null,
      "content": "圆神睌安",
      "origin": "madohomu.love",
      "deleted": 0,
      "createTime": 1770282864000,
      "username": null,
      "userUpdateTime": null,
      "liked": 0,
      "replies": []
    },
    {
      "id": 47092,
      "pid": 0,
      "userId": null,
      "externalId": 6656,
      "externalUserId": null,
      "externalUsername": "匿名用户",
      "likes": 0,
      "image": null,
      "avatar": null,
      "content": "圆神睌安",
      "origin": "madohomu.love",
      "deleted": 0,
      "createTime": 1770282273000,
      "username": null,
      "userUpdateTime": null,
      "liked": 0,
      "replies": []
    },
    {
      "id": 47036,
      "pid": 0,
      "userId": null,
      "externalId": 43232,
      "externalUserId": 6295,
      "externalUsername": "jojo",
      "likes": 0,
      "image": "",
      "avatar": null,
      "content": "圆神晚安",
      "origin": "kami.im",
      "deleted": 0,
      "createTime": 1770280440000,
      "username": null,
      "userUpdateTime": null,
      "liked": 0,
      "replies": []
    },
    {
      "id": 47035,
      "pid": 0,
      "userId": null,
      "externalId": 43231,
      "externalUserId": 4066,
      "externalUsername": "lormoveate",
      "likes": 0,
      "image": "",
      "avatar": null,
      "content": "圆神保佑~",
      "origin": "kami.im",
      "deleted": 0,
      "createTime": 1770262320000,
      "username": null,
      "userUpdateTime": null,
      "liked": 0,
      "replies": []
    },
    {
      "id": 47091,
      "pid": 0,
      "userId": null,
      "externalId": 6655,
      "externalUserId": 1554,
      "externalUsername": "L",
      "likes": 0,
      "image": null,
      "avatar": null,
      "content": "圆焰早安",
      "origin": "madohomu.love",
      "deleted": 0,
      "createTime": 1770261966000,
      "username": null,
      "userUpdateTime": null,
      "liked": 0,
      "replies": []
    }
  ]
}

export default {
  send: (data) => madokaPost("/message", data),
  // LR_小さな狐の妖精: 模拟数据开关
  list: (params) => USE_MOCK_DATA ? Promise.resolve(mockMessageData) : madokaGet("/message", params),
  getMaxId: () => madokaGet("/message/get-max-id"),
  getMaxTime: () => madokaGet("/message/get-max-time"),
  random: () => madokaGet("/message/random"),
  count: () => madokaGet("/message/count"),
  like: (messageId: number) => madokaPut("/message/like", { messageId }, { showSuccessMessage: false }),
}
